- .circleci/config.yml
- karma.conf.js
- package.json
- spec/fixtures/index.html
- spec/helpers/index.js
- spec/use-intersection_spec.js
- webpack.config.js
- yarn.lock
This PR adds Karma as a test runner and Mocha/Chai as a testing framework
A very basic test is added for the IntersectionController and a configuration file for CircleCI
fix #13
> Karma test runner setup

- spec/fixtures/index-application.html
- spec/use-application_spec.js
- src/use-application/use-application.ts
fix #26 
replace Object.assign with Object.defineProperty to define getters
> use defineProperty for getters instead of assign

- spec/helpers/index.js
- spec/use-click-outside/fixtures.js
- spec/use-click-outside/log_controller.js
- spec/use-click-outside/use-click-outside_spec.js
- spec/use-click-outside/use_log_controller.js
- src/use-click-outside/use-click-outside.ts
- src/use-idle/use-idle.ts
- src/use-intersection/use-intersection.ts
- src/use-resize/use-resize.ts
> Preserve this disconnect

- docs/use-debounce.md
- docs/use-throttle.md
- spec/use-debounce/fixtures.js
- spec/use-debounce/use-debounce_object_description_spec.js
- spec/use-debounce/use_log_object_description_controller.js
- spec/use-throttle/fixtures.js
- spec/use-throttle/use-throttle_spec.js
- spec/use-throttle/use_log_controller.js
- src/use-debounce/use-debounce.ts
- src/use-throttle/use-throttle.ts
If you need to set a different wait option for each function, you can specify it within the `throttles` array like so :
```js
export default class extends ApplicationController {
static throttles = [
'click',
{
name: 'fetch',
wait: 500
}
]
connect() {
useThrottle(this, { wait: 100 })
}
click() {
// this function is throttled with a wait time of 100ms.
}
fetch() {
// this function is throttled with a wait time of 500ms.
}
instant() {
// this function is not throttled.
}
}
```
> adds configurable wait throttle

- docs/use-debounce.md
- spec/use-debounce/fixtures.js
- spec/use-debounce/use-debounce_object_description_spec.js
- spec/use-debounce/use_log_object_description_controller.js
- src/use-debounce/use-debounce.ts
configurable wait time per function for debounce
```js
export default class extends ApplicationController {
static debounces = [
'click',
{
name: 'fecth',
wait: 500
}
]
connect() {
useDebounce(this, { wait: 100 })
}
click() {
// this function is debounced with a wait time of 100ms.
}
fetch() {
// this function is debounced with a wait time of 500ms.
}
instant() {
//this function is not debounced.
}
}
```
> useDebounce configurable per function wait time

- docs/application-controller.md
> Update the appliction controller example so it works.

- docs/use-dispatch.md
I noticed a small typo, so here's a PR with a fix.
Thanks for your amazing work, these mixins are great 👍
> Fix typo in docs/use-dispatch.md

- docs/_sidebar.md
- docs/debug.md
- docs/index.html
- docs/use-dispatch.md
- docs/use-visibility.md
- playground/index.html
- src/logger.ts
- src/stimulus_use.ts
- src/use-dispatch/use-dispatch.ts
- src/use-visibility/use-visibility.ts
Debug mode for useVisibility and a shorter debug messages using `groupCollapsed`
> Debug mode for use visibility

- spec/use-intersection/use-intersection_spec.js
> Fix flacky tests for useIntersection

- docs/use-debounce.md
> Fix typo in fetch

- README.md
- docs/_sidebar.md
- docs/observers.md
- docs/use-hover.md
- src/use-hover/hover-controller.ts
- src/use-hover/index.ts
- src/use-hover/use-hover.ts
Hi there,
Love this project, great work on it! :+1 
I ended up implementing this extra feature for my own projects so I thought I'd contribute it back if you're interested.
I've tried to match your style and code conventions. Let me know if you want me to make any changes.
> New Observer - useHover

- docs/use-dispatch.md
Hi,
Was just copy pasting, and came accross this typo
> Fix usedispatch type in documentation

- spec/use-intersection/use-intersection_spec.js
- spec/use-transition/fixtures.js
- spec/use-transition/log_controller.js
- spec/use-transition/use-transition_spec.js
- spec/use-transition/use_log_controller.js
- src/use-transition/use-transition.ts
very basic useTransition test suite foundation before addressing #110 and #111
> Use transition test suite foundation

- docs/use-transition.md
Hi!
I hope this can help the docs. This is all copy-and-pasted from a minimal, functional project - so it definitely works :).
Thank you!
> Adding a mixin & non-Tailwind example for useTransition

- src/use-target-mutation/use-target-mutation.ts
I realised I got errors when using target mutation because some library on my page adds HTML comments, this should fix it
> Don't try to process getAttribute on comment nodes

- package.json
relates to #156 
adds peerDependenciesMeta information as per @FlxAlbroscheit suggestion
> add peerDependenciesMeta for hotkeys

- package.json
- playground/package.json
- yarn.lock
relates to #156 
temporary fix by adding hotkeys-js as a real dependency
> make hotkeys-js a real dependency as a hotfix

- package.json
@adrienpoly I havent had the chance to test this as im currently quite limited on time, but give this a whirl and let me know if this fixes the issues you were facing with tree-shaking.
> chore: change "main" to a module instead of UMD.

- .github/workflows/tests.yml
- karma.conf.js
Additionally:
* Don't depend on SauceLabs for now
* Bump `actions/setup-node` and `actions/checkout` to `v3`
> Use GitHub Action for JavaScript Tests

- .github/workflows/treeshake.yml
Since we have the ability to test the treeshake compatibility it could make sense to test that also in CI.
Feel free to close this one as well if you think this doesn't make sense.
> Check treeshake compatibility in CI

- docs/use-transition.md
> Fix typo in use-transition.md

- src/use-window-focus/use-window-focus.ts
> Remove unnessary log

- .github/scripts/publish-dev-build
- .github/workflows/dev-builds.yml
This pull request adds a GitHub Actions workflow for creating stimulus-use dev-builds at https://github.com/stimulus-use/dev-builds
> Add dev-builds

- docs/use-intersection.md
- package.json
- playground/index.js
- spec/use-intersection/use-intersection_spec.js
- yarn.lock
Hopefully this is what you meant by #558. If not, let me know and I'd be happy to take another crack at it.
> chore(useIntersection)!: Remove intersection observer polyfill (Fixes #558)
