package.json
Hey @adrienpoly,
Thanks for creating this project! I'm looking forward to contribute to `stimulus-use`. 
While following your instructions to setup the project locally, I noticed that `rimraf` was missing. I got the following error while running `yarn build`:
```
stimulus-use on master via v10.16.0
❯ yarn build
yarn run v1.22.4
$ yarn clean
$ rimraf dist *.tsbuildinfo
/bin/sh: rimraf: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I guess it's missing. After adding `rimraf` as a `devDependecy` to project built successfully.
=> Add rimraf as devDependency

docs/application-controller.md, playground/controllers/cart_controller.js, src/use-application/use-application.ts
When using `this.dispatch`  function from the application-controller it does automatically add the emitting controller to the `detail` of the event
```js
refreshTotal(e) {
this.counter++
console.log(e.detail.controller) // the item_controller
}
```
=> adds the emitting controller to the custom event

playground/index.html, src/use-click-outside/click-outside-controller.ts, src/use-click-outside/use-click-outside.ts, src/use-idle/idle-controller.ts, src/use-idle/use-idle.ts, src/use-intersection/intersection-controller.ts, src/use-intersection/use-intersection.ts, src/use-lazy-load/lazy-load-controller.ts, src/use-lazy-load/useLazyLoad.ts, src/use-resize/resize-controller.ts, src/use-resize/use-resize.ts
fix #45 
Rather than assigning `observe` and `unobserve` to the controller this PR modifies the global API for observer mixins.
The mixin now returns the observe and unobserve function if needed
```js
const [observe, unobserve] = useResize(this, options)
```
The default controller for each mixin also have these default function assigned
=> fix observers are being overwritten

README.md, docs/_sidebar.md, docs/application.md, docs/stu-playground.md, docs/use-dispatch.md, playground/controllers/cart_controller.js, playground/controllers/item_controller.js, spec/fixtures/index-application.html, spec/use-application_spec.js, src/index.ts, src/use-application/application-controller.ts, src/use-application/use-application.ts, src/use-dispatch/index.ts, src/use-dispatch/use-dispatch.ts
`dispatch` function was part of the `ApplicationController` and didn't really get the required visibility.
This PR extract it to it's own mixin
```js
// item_controller.js
import { Controller } from 'stimulus'
import { useDispatch } from 'stimulus-use'
export default class extends Controller {
connect() {
usedispatch(this)
}
add() {
// dispatch a custom event item:add with a delatil payload of {quantity: 1}
this.dispatch("add", {quantity: 1})
}
}
```
=> Extract useDispatch

docs/index.html
Issue: when clicking on the website's project logo/name it goes to a 404. This is because it tries to go to `"/"` instead of `"/stimulus-use/"`. I am not familiar at all with Docsify, but I believe this might be related to [the option `basePath`](https://docsify.js.org/#/configuration?id=basepath).
I haven't been able to actually test it so I don't know if this actually works, please verify it before accepting/merging. I can try to verify it later/tomorrow otherwise.
Context: https://twitter.com/FPresencia/status/1335585928954474499
=> Fixed homepage link

src/use-idle/use-idle.ts, src/use-intersection/use-intersection.ts, src/use-resize/use-resize.ts, src/use-visibility/use-visibility.ts
When calculating options using defaultOptions, the first argument of Object.assign should be {}.
Otherwise the defaultOptions itself would be rewritten.
Thanks for maintaining a great product!
=> Avoid overriding defaultOptions directly

docs/use-click-outside.md, spec/use-click-outside/fixtures.js, spec/use-click-outside/use-click-outside_spec.js, src/support/index.ts
closes #103 
as reported in #103 click outside callback would not trigger if the element is partially in the view port. This was not the intended behavior. Only element completely outside the viewport should not trigger a callback is the option onlyVisible is set to true.
=> fix click outside for partially visible element

src/use-throttle/use-throttle.ts
Hiya, 
Small typo fix I found when I was working on https://github.com/stimulus-use/stimulus-use/pull/105
=> Fix typo in ThrottleController, "trottles" instead of "throttles"

src/support/index.ts, src/use-application/application-controller.ts, src/use-application/use-application.ts, src/use-click-outside/click-outside-controller.ts, src/use-click-outside/use-click-outside.ts, src/use-debounce/use-debounce.ts, src/use-hover/hover-controller.ts, src/use-hover/use-hover.ts, src/use-idle/idle-controller.ts, src/use-idle/use-idle.ts, src/use-intersection/intersection-controller.ts, src/use-intersection/use-intersection.ts, src/use-lazy-load/lazy-load-controller.ts, src/use-lazy-load/useLazyLoad.ts, src/use-mutation/mutation-controller.ts, src/use-mutation/use-mutation.ts, src/use-resize/resize-controller.ts, src/use-resize/use-resize.ts, src/use-throttle/use-throttle.ts, src/use-transition/transition-controller.ts, src/use-transition/use-transition.ts, src/use-visibility/use-visibility.ts, src/use-visibility/visibility-controller.ts, src/use-window-resize/use-window-resize.ts, src/use-window-resize/window-resize-controller.ts
Hiya, 
Using a few of these in my Typescript projects. By describing the methods like they are currently
```
options!: *Functionality*Options
observe!: () => void
unobserve!: () => void
```
extending the controllers works fine, but it throws errors if a controller tries mixing in `use*Functionality*` without implementing all of them. 
Might just be my usage of them, but I found myself having to declare `observe` and `unobserve` on my controller even though I don't use them. And unless the user is extending the class - having a class property called `options` should be optional, given that mixin method allows passing inline options.
I've made changes so that the "extending" mode properties are not expected on the mixin function call signatures. 
---
Also fixed the type of `setTimeout` in …
=> Fix typing information for pre-declared methods that are added by the enhancement functions

docs/_sidebar.md, docs/use-transition.md, playground/controllers/dropdown_controller.js, playground/controllers/transition_controller.js, playground/index.html, spec/helpers/index.js, spec/use-intersection/use-intersection_spec.js, spec/use-transition/fixtures.js, spec/use-transition/use-transition_spec.js, src/use-transition/use-transition.ts
- Close #110 by introducing a new option `removeToClasses` (default to true) that will remove the `To` classes once the transition is finished
- adds support for preserving initial classes as reported by @jduff in #77
- Relates #108 only a basic documentation for now. 
I think this should fix quite a few strange behavior I have seen with the mixin. 
The next step is to make all options available as directives
=> Fix use transition enter leave

docs/use-transition.md, playground/controllers/dropdown_controller.js, playground/controllers/transition_controller.js, spec/use-transition/fixtures.js, spec/use-transition/use-transition_spec.js, src/use-transition/use-transition.ts
close #116
use the new Vue3 syntax adding `from` suffix
`enter` become `enterFrom`
`leave` becomes `leavFrom`
=> rename enter/leave classe from Vue2 syntax to Vue3

src/stimulus-use.ts
I noticed that when using a custom `eventPrefix` that the `dispatch()` function logs the wrong `eventName`. 
If you check the log messages in the dev tools and expand the details you will see the the the `eventName` is logged without the prefix while the right eventName (with the prefix) is actually emitted. 
This PR fixes the log output to match the actual dispatched event.
=> log correct event name in `dispatch()` when using `eventPrefix`

spec/use-application_spec.js, src/use-application/use-application.ts
Hiya,
Just spotted that this hasn't been updated to support Hotwire/Turbo (https://turbo.hotwire.dev/handbook/building#detecting-when-a-preview-is-visible) 
Thought I'd pop out a quick PR if you want it.
=> ApplicationController isPreview - Add support for Hotwire/Turbo

docs/application-controller.md, src/use-application/application-controller.ts, src/use-application/use-application.ts
This PR adds a `isConnected` helper function the the `ApplicationController`.
This helper function can be used to detect whether a Stimulus controller is connected or not.
```js
import { ApplicationController } from 'stimulus-use'
export default class extends ApplicationController {
initialize() {
console.log("initialize", this.isConnected) // => false
}
connect() {
console.log("connect", this.isConnected) // => true
}
anyOtherAction() {
console.log("anyOtherAction", this.isConnected) // => true
}
disconnect() {
console.log("disconnect", this.isConnected) // => false
}
}
```
=> Add `isConnected` helper to `ApplicationController`

src/use-dispatch/use-dispatch.ts, src/use-mutation/use-mutation.ts
The StimulusUse base class already provides this property.
=> clean: remove redundant targetElement property

src/use-idle/use-idle.ts
I wanted to use useIdle in my project, in which I work with rails, turbo and stimulus. When I navigate with Turbo between two pages, both with a useIdle instance, the away event is dispatched multiple times, because the timer is not stopped on disconnect / unobserve.
=> clears timeout on unobserve

src/support/index.ts
Hi!
The function [`isElementInViewport`] don't work as expected because is detecting the element in the viewport when it is not.
When an element is hidden (display: none) this is its size and position (checked on FF and Chrome): 
```js
DOMRect { x: 0, y: 0, width: 0, height: 0, top: 0, right: 0, bottom: 0, left: 0 }
```
While when using a tailwind class like `-translate-x-full` (checked on FF):
```js
DOMRect { x: -448, y: 0, width: 448, height: 419, top: 0, right: 0, bottom: 419, left: -448 }
```
The function should not return true when the result of `rect.top + rect.height` or `rect.left + rect.width` is zero.
Thanks!
=> Fix isElementInViewport

src/use-debounce/use-debounce.ts
- make DebounceOptions optional for useDebounce to match docs
- fix typing to match parsing logic, should be array (string | opts) vs (array of string) | (array of opts)
- type constructor more precisely in useDebounce which removes need for optional chaining
=> Update useDebounce to provide default (empty) DebouceOptions matching documentation and improving DX

docs/use-intersection.md, src/use-intersection/intersection-controller.ts, src/use-intersection/use-intersection.ts
As pointed out by @ocarreterom the `useIntersection` mixin would just fire the `disappear` event once when the mixin is being used with multiple elements in the same controller.
This PR fixes this issue by moving the tracking reference from the controller instance to each element which is being tracked.
https://user-images.githubusercontent.com/6411752/183229395-bf4b37b6-16b3-465a-a62d-eee9f43f1c9d.mp4
Resolves #211
=> Fix `useIntersection` for multiple elements in the same controller

src/use-transition/use-transition.ts
I think I found a small bug in this mixin where the `defaultOptions` object was getting overridden with values from callers due how `Object.assign` was being used.
I think the fix is to just assign the defaults and then the caller options to a new object.
=> fix: use-transition default options assignment

package.json, yarn.lock
Very small PR that adds the `docsify-cli` npm package to the `devDependencies`.  
Without this you had to have docsify installed locally, to be able to execute the command `yarn doc`
=> Add missing `docsify-cli` devDependency

cypress/integration/use-window-resize.spec.js, docs/application-controller.md, docs/use-dispatch.md, docs/use-transition.md, playground/index.html
closes #229 
This PR updates the targets to the new Stimulus 2 syntax.
In the docs as wells as in the playground/index.html
=> Update deprecated Stimulus 1 target-syntax

docs/application-controller.md, docs/application.md, docs/debug.md, docs/use-dispatch.md, src/stimulus-use.ts, src/use-dispatch/use-dispatch.ts
closes #206 
Is the deprecation message good enough?
```
useDispatch() is a deprecated mixin from Stimulus-Use. Please use the built-in dispatch() function from Stimulus: https://stimulus.hotwired.dev/reference/controllers#cross-controller-coordination-with-events
```
Two questions:
1. Should other docs also be updated?
- docs/application-controller.md
- docs/application.md
- docs/debug.md
2. Should a "deprecation" file be created, to track the deprecation cycle?
=> Mark `useDispatch` as deprecated

docs/application-controller.md, src/use-application/use-application.ts
This Pull Request adds a `overwriteDispatch` option to `useApplication()` in order to be able to control if `useApplication` should call the deprecated `useDispatch()` behavior or not. 
Previously if you were using `useApplication()` it would always override the built-in Stimulus `this.dispatch()` function inside the controller.
The `overwriteDispatch` option is set to `true` by default so that it doesn't break backwards-compatibility, but you probably anyway just want to call `useApplication()` with this option if you want to disable the overwrite:
```js
import { Controller } from "@hotwired/stimulus"
import { useApplication } from "stimulus-use"
export default class extends Controller {
connect() {
useApplication(this, { overwriteDispatch: false })
}
}
```
=> Add `overwriteDispatch` option to `useApplication()`

spec/use-debounce/fixtures.js, spec/use-debounce/use-debounce_spec.js, spec/use-debounce/use_log_controller.js, src/use-debounce/index.ts, src/use-debounce/use-debounce.ts
The way Stimulus invokes controller actions doesn't account for debounced actions. Since stimulus-use is rewriting the actual controller action of the Controller and therefore also executing the action after the specifed debounce time, there is enough time for the browser the re-assign the `params` object on the `event`.
But this actually just happened and mattered if the same actual event was used for triggering multiple actions, the order was right and the controller action relied on the `event.params` to be right.
Context:
https://github.com/hotwired/stimulus/blob/38cefb4cad01e8af9288cad1a1fedb41b3b1383a/src/core/binding.ts#L72
Fixes #251 
Special thanks to @KonnorRogers for rubber ducking this issue! ❤️ 
I had a few solutions which fixed this issue upstream in Stimulus itself, but I …
=> `useDispatch`: Fix params for debounced actions if event is shared

src/use-click-outside/use-click-outside.ts
I'm having this funny issue with states when playing with elements that are shown/hidden by an "outsider" element. 
```html
<div id="sidebar" data-controller="sidebar"></div>
<div id="burger"></div>
```
The `burger` element opens the sidebar, being outside the sidebar controller/element scope. The `sidebar` controller uses `clickOutside` to close/hide the sidebar if it's open. When clicking the burger, it changes the state of the sidebar and opens it making it visible with in the viewport. And then `clickOutside` is triggered closing it again (as it's visible within the viewport now and the state has just changed). `open -> clickOutside -> close`
As workaround I've been adding a delay of 1ms to execute the lines that changes the state of the sidebar, then `clickOutside` don't even trigger …
=> Trigger clickOutside first!

.npmignore, docs/use-hotkeys.md, package.json, playground/controllers/hotkeys_controller.js, playground/vite.config.js, rollup.config.js, spec/use-hotkeys/use_log_controller.js, src/hotkeys.ts, src/index.ts, yarn.lock
This pull request moves the `useHotkeys()` behavior to separate file, so that the main bundle doesn't include `hotkeys-js` as a NPM dependency.
If you are using `useHotkeys()` in your application and you are upgrading to the next version (likely `v0.52.0`) you have to change the import for the `useHotkeys()` behavior.
```diff
-import { useHotkeys } from "stimulus-use"
+import { useHotkeys } from "stimulus-use/hotkeys"
```
Also, please add `hotkeys-js` as a npm dependency to your application if you haven't added it yet, it's not being removed as a runtime  dependency.
The existing import (`import { useHotkeys } from "stimulus-use"`) will throw an error in the new version, so that people know how to upgrade (if we don't throw the error here it would throw an error down the stack, because …
=> Extract `useHotkeys()` and remove `hotkeys-js` as dependency

docs/use-intersection.md, src/use-intersection/intersection-controller.ts, src/use-intersection/use-intersection.ts
This pull request allows the callbacks from the `useIntersection` behavior to access the `IntersectionObserver` as the second argument in the callback.
This enables things like this:
```js
export default class extends Controller { 
connect() {
useIntersection(this)
}
appear(entry, observer) {  
observer.unobserve(entry.target)
}
}
```
This allows you to call all available methods directly on the `observer` itself to implement the logic according to your needs. In this case it would allow to only trigger the `appear` callback once.
This enables a more elegant solution for https://github.com/stimulus-use/stimulus-use/issues/370
=> Pass `IntersectionObserver` instance to `useIntersection` callbacks

README.md
Converting to markdown syntax removes the underline you can see in the attached screenshot! it's a small detail but I find it really annoying! 
before:
after:
=> fix: convert html syntax to markdown syntax in readme

README.md, docs/use-hotkeys.md
I noticed that the links to the Hotkeys-js library were broken, so I fixed them.
It might be interesting to link directly to the Github repository rather than the official site? what do you think? 
I'll make the change if you prefer.
=> Fix broken links to hotkeys-js

docs/use-target-mutation.md
Doc had spaces between bold markdown symbols, resulting it displaying ** ** instead of actual bold text. Also changed instances of the word 'removed' to 'changed' for clarity to match the appropriate method.
I would also suggest using header markdown symbols instead of bolding the titles where appropriate.
=> Fix minor errors in use-target-mutation doc

docs/use-target-mutation.md, src/use-target-mutation/use-target-mutation.ts
This PR adds a depreciation mention for `[target]TargetAdded` and `[target]TargetRemoved` as their behavior appears to be identical to `[target]TargetConnected` and `[target]TargetDisconnected`.
Feel free to close if it's not 😉 !
=> `useTargetMutation`: Add deprecation mention for `[target]TargetAdded` and `[target]TargetRemoved`

src/use-click-outside/use-click-outside.ts
I'm seeing cases where an error arises from assuming `event.target` is always a `Node`:
```
TypeError: Argument 1 ('other') to Node.contains must be an instance of Node
```
I'd like to propose adding an extra check here so it doesn't fail if it is `Window` for instance.
=> Extra type safety check in use-click-outside
